In [1]:
import numpy as np 

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=np.array([(1,2,3),(4,5,6)],dtype=float)
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
c=np.array([(1.5,4,5),(4,6,7),(4,9,8)], dtype=float)
c

array([[1.5, 4. , 5. ],
       [4. , 6. , 7. ],
       [4. , 9. , 8. ]])

In [11]:
np.zeros((3,4)) 
#create array of zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4),dtype=np.int16)
#create array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
d=np.arange(10,25,5)
d
#create array of evenly spaced step value

array([10, 15, 20])

In [19]:
np.linspace(0,2,9)
#create array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
e=np.full((2,2),7)
#create a constant array

In [21]:
e

array([[7, 7],
       [7, 7]])

In [24]:
#create 2x2 identity matrix
f=np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.random((2,2))

array([[0.64772322, 0.0127585 ],
       [0.8552495 , 0.61262937]])

In [27]:
np.empty((3,2))
#create an empty array

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

# I/O

### Saving & Loading on Disk

In [28]:
np.save('my_array',a)

In [37]:
np.savez('array.pnz',a,b)

In [31]:
np.load('my_array.npy')

array([1, 2, 3])

In [39]:
np.load('array.pnz.npz')

### Saving and Loading Text files

In [67]:
np.genfromtxt("salary_data.csv", delimiter=',')

array([[        nan,         nan],
       [1.10000e+00, 3.93430e+04],
       [1.30000e+00, 4.62050e+04],
       [1.50000e+00, 3.77310e+04],
       [2.00000e+00, 4.35250e+04],
       [2.20000e+00, 3.98910e+04],
       [2.90000e+00, 5.66420e+04],
       [3.00000e+00, 6.01500e+04],
       [3.20000e+00, 5.44450e+04],
       [3.20000e+00, 6.44450e+04],
       [3.70000e+00, 5.71890e+04],
       [3.90000e+00, 6.32180e+04],
       [4.00000e+00, 5.57940e+04],
       [4.00000e+00, 5.69570e+04],
       [4.10000e+00, 5.70810e+04],
       [4.50000e+00, 6.11110e+04],
       [4.90000e+00, 6.79380e+04],
       [5.10000e+00, 6.60290e+04],
       [5.30000e+00, 8.30880e+04],
       [5.90000e+00, 8.13630e+04],
       [6.00000e+00, 9.39400e+04],
       [6.80000e+00, 9.17380e+04],
       [7.10000e+00, 9.82730e+04],
       [7.90000e+00, 1.01302e+05],
       [8.20000e+00, 1.13812e+05],
       [8.70000e+00, 1.09431e+05],
       [9.00000e+00, 1.05582e+05],
       [9.50000e+00, 1.16969e+05],
       [9.60000e+00,

In [71]:
np.savetxt("text.txt",c,delimiter=" ")

In [72]:
np.loadtxt("text.txt")

array([[1.5, 4. , 5. ],
       [4. , 6. , 7. ],
       [4. , 9. , 8. ]])

In [74]:
#asking for help 
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### inspecting array 

In [77]:
b.shape

(2, 3)

In [79]:
len(c)

3

In [81]:
b.ndim #number of array dimensions

2

In [85]:
b.size #number of array elements

6

In [87]:
b.dtype #data type of array elements

dtype('float64')

In [88]:
b.dtype.name #name of data type

'float64'

In [90]:
b.astype(int) #convert array to different type

array([[1, 2, 3],
       [4, 5, 6]])

### data types

In [92]:
np.int64 #Signed 64-bit integer types

numpy.int64

In [93]:
np.float32 #Standard double-precision floating point

numpy.float32

In [95]:
np.complex #complex numbers represented  by 128 floats 

C:\Users\ndhan\AppData\Local\Temp\ipykernel_22776\1983443731.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #complex numbers represented  by 128 floats


complex

In [97]:
np.bool #stores true and false values

C:\Users\ndhan\AppData\Local\Temp\ipykernel_22776\3337323189.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool #stores true and false values


bool

In [102]:
np.object # python object type 

C:\Users\ndhan\AppData\Local\Temp\ipykernel_22776\2067865337.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object # python object type


object

In [103]:
np.string_  # fixed length string type 

numpy.bytes_

In [104]:
np.unicode_   # fixed length unicode type 

numpy.str_

## Array Mathematics

#### Arthmetic Operations 

In [111]:
g = a-b  # subtraction 
g

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [110]:
np.subtract(a,b) #subtraction

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [113]:
a+b #Addition

array([[2., 4., 6.],
       [5., 7., 9.]])

In [115]:
np.add(a,b) #Addition

array([[2., 4., 6.],
       [5., 7., 9.]])

In [117]:
a/b #Division

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [121]:
np.divide(a,b) #Division

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [122]:
a*b #Multiplication

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [124]:
np.multiply(a,b) #Multiplication

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [126]:
np.exp(b) #Exponentiation

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [129]:
np.sqrt(c) #Square root

array([[1.22474487, 2.        , 2.23606798],
       [2.        , 2.44948974, 2.64575131],
       [2.        , 3.        , 2.82842712]])

In [131]:
np.sin(a) #print sines of an array 

array([0.84147098, 0.90929743, 0.14112001])

In [132]:
np.cos(a) #element wise cosine

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [133]:
np.log(a) #element wise natural logarithm 

array([0.        , 0.69314718, 1.09861229])

In [135]:
e.dot(b) #dot product 

array([[35., 49., 63.],
       [35., 49., 63.]])

### comparison

In [139]:
a==b #element wise comparison

array([[ True,  True,  True],
       [False, False, False]])

In [138]:
a<3  ##element wise comparison

array([ True,  True, False])

In [140]:
np.array_equal(a,b) #array-wise comparison

False

### aggregate functions

In [144]:
a

array([1, 2, 3])

In [145]:
a.sum()

6

In [146]:
a.min()

1

In [151]:
c

array([[1.5, 4. , 5. ],
       [4. , 6. , 7. ],
       [4. , 9. , 8. ]])

In [152]:
c.max(axis=0)

array([4., 9., 8.])

In [157]:
c.cumsum(axis=1) #cumulative sum of elements   axis 1 is previous column wise add

array([[ 1.5,  5.5, 10.5],
       [ 4. , 10. , 17. ],
       [ 4. , 13. , 21. ]])

In [158]:
c.cumsum(axis=0) #axis 0 add above row wise 

array([[ 1.5,  4. ,  5. ],
       [ 5.5, 10. , 12. ],
       [ 9.5, 19. , 20. ]])

In [159]:
a.mean()

2.0

In [162]:
np.median(b)

3.5

In [164]:
np.corrcoef(a) #correlation coeff

1.0

In [166]:
np.std(b) #std deviation

1.707825127659933

## Copying array 

- the copy is the new array whereas the view is the view of the original array
- deep copy is a complete copy of the array and its data, and doesn’t share with the original array.

In [169]:
h= a.view() #create view of array with same data 
h

array([1, 2, 3])

In [170]:
np.copy(a) #create copy of array 

array([1, 2, 3])

In [172]:
h=a.copy() #create deep copy of array 

### Sorting Arrays 

In [195]:
arr = np.array([3, 2, 0, 1])

np.sort(arr)


array([0, 1, 2, 3])

In [201]:
print(np.sort(f, axis=0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [202]:
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Subsetting, slicing, indexing

#### Subsetting

In [205]:
f[2]

array([0., 0., 1., 0.])

In [209]:
c[2,2]

9.0

In [207]:
c

array([[1.5, 4. , 5. ],
       [4. , 6. , 7. ],
       [4. , 8. , 9. ]])

#### slicing

In [211]:
#select items at index 0 and 1 
a[0:2]

array([1, 2])

In [216]:
c[0:2,2] #Select items at rows 0 and 1 in column 1

array([5., 7.])

In [215]:
c

array([[1.5, 4. , 5. ],
       [4. , 6. , 7. ],
       [4. , 8. , 9. ]])

In [219]:
c[:1]  #Select all items at row 0 (equivalent to b[0:1, :]

array([[1.5, 4. , 5. ]])

In [221]:
c[1,...] #same as [1,:,:]

array([4., 6., 7.])

In [224]:
c[::-1] #reversed array

array([[4. , 8. , 9. ],
       [4. , 6. , 7. ],
       [1.5, 4. , 5. ]])

### boolean indexing

In [227]:
c[c<2]  #select elements less than 2 

array([1.5])

#### fancy indexing 

In [228]:
 b[[1, 0, 1, 0],[0, 1, 2, 0]] #select elements (1,0),(0,1),(1,2) and (0,2)

array([4., 2., 6., 1.])

In [229]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [230]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #selecct a subset of matrix's rows and columns

array([[4., 5., 6., 4.],
       [1., 2., 3., 1.],
       [4., 5., 6., 4.],
       [1., 2., 3., 1.]])

## Array Manipulation

In [237]:
# Transposing array
i=np.transpose(b)
i

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [238]:
a.T

array([1, 2, 3])

In [245]:
#changing array shape
b.ravel() #flatten array 
g.reshape(3,-2) #reshaoe but dnt change data 

array([[ 0.,  0.],
       [ 0., -3.],
       [-3., -3.]])

In [244]:
 g

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [248]:
#adding/removing elements 
h.resize(2,6) #return a new array with shape(2,6)

In [249]:
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [251]:
np.append(h,g) #append items to an array 

array([ 1.,  2.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -3., -3., -3.])

In [255]:
np.insert(a,1,5) #insert item in an array 

array([1, 5, 2, 3])

In [256]:
np.delete(a,[1]) #delete items from an array

array([1, 3])

In [257]:
a

array([1, 2, 3])

In [258]:
#combining arrays

In [259]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [260]:
d

array([10, 15, 20])

In [262]:
np.vstack((a,b)) # stock arrays row-wise

array([[1., 2., 3.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [269]:
np.r_[b,g] #stack arrays vertifically (row-wise)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [272]:
np.hstack((b,g)) #stack horizontally (column-wise)

array([[ 1.,  2.,  3.,  0.,  0.,  0.],
       [ 4.,  5.,  6., -3., -3., -3.]])

In [275]:
np.column_stack((a,d)) #create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [277]:
np.c_[a,d]  #create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [278]:
#Splitting arrays

In [280]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [283]:
np.vsplit(f,2) #split the array vertically at the 2nd index

[array([[1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 array([[0., 0., 1., 0.],
        [0., 0., 0., 1.]])]