In [1]:
1+1

2

In [3]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [4]:
type(8.9)

float

In [7]:
import pandas #import package without an alias

In [8]:
import pandas as pd #with alias

In [11]:
from pandas import DataFrame #import an object from a package

In [12]:
# working directory

In [20]:
import os #import the operating system package 

In [22]:
os.getcwd #get current directory 

<function nt.getcwd()>

In [23]:
os.chdir("C:/") #set the working directory to a new file path 

# Operartors

#### arthmetic operator 

In [24]:
102+45

147

In [25]:
234-56

178

In [26]:
4*6

24

In [39]:
23/7 #divide returns float 

3.2857142857142856

In [38]:
23//7 #integer divide

3

In [34]:
2^6 #xOR

4

In [36]:
2**3

8

In [37]:
23%7 #returns remainder


2

#### assignment operators

In [47]:
a =5 #assign value 
a

5

In [49]:
x=[4,5,6,7]

In [50]:
x[0] = 3 #change the value of item in a list 

In [51]:
x

[3, 5, 6, 7]

#### Numeric comparison operators 

In [52]:
3 == 3

True

In [53]:
3!=3

False

In [54]:
3>2

True

In [55]:
3>=3

True

In [56]:
3<6

True

In [57]:
3<=4

True

#### Logical operators 

In [62]:
~ (2 == 2)

-2

In [64]:
(1!=1)&(1<1) #and

False

In [65]:
(1>=1)|(1<1) #or

True

In [66]:
(1!=1)^(1<1) #xor

False

# Getting started with lists 

In [18]:
y=[1,3,2] # create list 

In [19]:
sorted(y) #return a sorted copy of list 

[1, 2, 3]

In [20]:
y.sort() #sorts the list in-place (replaces x)
#print(y)

In [21]:
print(y)

[1, 2, 3]


In [44]:
l=[5,9,7,9]

In [45]:
l.reverse() # reverses the sorting order of the elements.

In [46]:
print(l)

[9, 7, 9, 5]


In [48]:
l.count(9) # number of times 9 appears in the list l 

2

#### selecting list elements /

In [49]:
l

[9, 7, 9, 5]

In [50]:
l[0]

9

In [51]:
l[-1]

5

In [52]:
l[1:3]

[7, 9]

In [53]:
l[2:]

[9, 5]

In [54]:
l[:3]

[9, 7, 9]

#### concatenating list

In [55]:
m=[10,20,30,40]

In [56]:
l

[9, 7, 9, 5]

In [57]:
l+m

[9, 7, 9, 5, 10, 20, 30, 40]

In [58]:
4*m

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]

# Getting started with dictionaries

In [60]:
dict={'a':1, 'b':2, 'c':3, 'd':4}

dict

In [62]:
dict.keys()

dict_keys(['a', 'b', 'c', 'd'])

In [63]:
dict.values()

dict_values([1, 2, 3, 4])

In [65]:
dict.items()

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])

In [66]:
dict['c']

3

# Numpy arrays 

NumPy is a python package for scientific computing. It provides multidimensional array objects and efficient operations 
on them. To import NumPy, you can run this Python code import numpy as np

### creating arrays 

In [67]:
import numpy as np 

In [68]:
np.array([1,2,3])

array([1, 2, 3])

In [75]:
#  Return a sequence from start (inclusive) to end (exclusive)
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
np.arange(1,9,2)  #(start, stop, step)

array([1, 3, 5, 7])

In [81]:
#np.arange? #? for syntax help 

In [84]:
np.repeat([1,3,5],3)  #repeat values n times 

array([1, 1, 1, 3, 3, 3, 5, 5, 5])

In [86]:
np.tile([1,2,4],5) #repeat tile n times

array([1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4])

# Math functions and methods using Numpy

In [87]:
np.log(m)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [88]:
np.exp(m)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [89]:
np.max(l)

9

In [90]:
np.min(l)

5

In [91]:
np.sum(m)

100

In [92]:
np.mean(m)

25.0

In [103]:
np.quantile(m, 0.5) #calculate q-th quantile

25.0

In [101]:
m

[10, 20, 30, 40]

In [105]:
np.round(m,2)  #round to n decimal places

array([10, 20, 30, 40])

In [107]:
np.var(m) #calculate variance

125.0

In [109]:
np.std(m) #calculate std deviation

11.180339887498949

# Getting started with characters and strings


In [110]:
"Datacamp"

'Datacamp'

In [112]:
"He said, \"Datacamp\""

'He said, "Datacamp"'

In [118]:
# Create multi line strings with triple quotes
str="""
A Frame of Data

Tidy, Mine, Analyze It 

Now You Have Meaning

Citation: https://mdsr book.github.io/haikus.html
"""

In [121]:
str[2]

' '

In [122]:
str[3]

'F'

In [124]:
str[0] # Get the character at a specific position

'\n'

In [133]:
str[2:10] #10 not included

' Frame o'

### combining and splitting strings

In [134]:
#concstenate strings with +
"Data" + "Camp"

'DataCamp'

In [140]:
#repeat string 3 times 
3 * "Victory belongs to Nikita "

'Victory belongs to Nikita Victory belongs to Nikita Victory belongs to Nikita '

In [142]:
"beekeepers".split("e") #Split a string to characters on a delimiter, returns without any e 

['b', '', 'k', '', 'p', 'rs']

### Mutate String

In [155]:
poem = "Johny johny yes papa"

In [156]:
poem.upper()

'JOHNY JOHNY YES PAPA'

In [157]:
poem.lower()

'johny johny yes papa'

In [158]:
poem.title()

'Johny Johny Yes Papa'

In [161]:
poem.replace("j","d")

'Johny dohny yes papa'

# Getting Started with DataFrames using Pandas

Pandas is a fast and powerful package for data analysis and manipulation in python. To import the package, you can 
use import pandas as pd. A pandas DataFrame is a structure that contains two-dimensional data stored as rows and 
columns. A pandas series is a structure that contains one-dimensional data.

In [162]:
import pandas as pd

In [164]:
# create a dataframe from a dictionary
pd.DataFrame({
    'a':[1,2,3],
    'b':np.array([4,4,6]),
    'c':['x','y','z']
})

a  b  c
0  1  4  x
1  2  4  y
2  3  6  z

In [172]:
# create a dataframe from a list of dictionaries
pd.DataFrame([
    {'a':1, 'b':4, 'c':'x'},
    {'a':2, 'b':4, 'c':'y'},
    {'a':3, 'b':6, 'c':'z'}
])

a  b  c
0  1  4  x
1  2  4  y
2  3  6  z

### Selecting DataFrame Elements

In [175]:
df = pd.read_csv('iris.csv')
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [174]:
# Select 3rd row 
df.iloc[3]

5.1                    5.0
3.5                    3.6
1.4                    1.4
0.2                    0.2
Iris-setosa    Iris-setosa
Name: 3, dtype: object

In [179]:
#selct one column by name
df['Iris-setosa']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: Iris-setosa, Length: 149, dtype: object

In [180]:
#select multiple columns by names 
df[['1.4','3.5']]

1.4  3.5
0    1.4  3.0
1    1.3  3.2
2    1.5  3.1
3    1.4  3.6
4    1.7  3.9
..   ...  ...
144  5.2  3.0
145  5.0  2.5
146  5.2  3.0
147  5.4  3.4
148  5.1  3.0

[149 rows x 2 columns]

In [182]:
# select 2nd column and all rows 
df.iloc[:,2]

0      1.4
1      1.3
2      1.5
3      1.4
4      1.7
      ... 
144    5.2
145    5.0
146    5.2
147    5.4
148    5.1
Name: 1.4, Length: 149, dtype: float64

In [185]:
#select the element in the 3rd row , 2nd column 
df.iloc[3,2]

1.4

### Manipulating DataFrames

In [190]:
df1=pd.read_csv('mvt.csv')
df1

Date   Latitude  Longitude
0       12/31/12 23:15  41.756284 -87.621645
1       12/31/12 22:00  41.898788 -87.661303
2       12/31/12 22:00  41.969186 -87.767670
3       12/31/12 22:00  41.769329 -87.657726
4       12/31/12 21:30  41.837568 -87.621761
...                ...        ...        ...
191636     1/1/01 0:05  41.887566 -87.711323
191637     1/1/01 0:01  41.981924 -87.658878
191638     1/1/01 0:01  41.799024 -87.696538
191639     1/1/01 0:01  41.971437 -87.727056
191640     1/1/01 0:01  41.968327 -87.696388

[191641 rows x 3 columns]

In [194]:
#concatenante dataframe vertically
pd.concat([df, df1]) 

5.1  3.5  1.4  0.2  Iris-setosa         Date   Latitude  Longitude
0       4.9  3.0  1.4  0.2  Iris-setosa          NaN        NaN        NaN
1       4.7  3.2  1.3  0.2  Iris-setosa          NaN        NaN        NaN
2       4.6  3.1  1.5  0.2  Iris-setosa          NaN        NaN        NaN
3       5.0  3.6  1.4  0.2  Iris-setosa          NaN        NaN        NaN
4       5.4  3.9  1.7  0.4  Iris-setosa          NaN        NaN        NaN
...     ...  ...  ...  ...          ...          ...        ...        ...
191636  NaN  NaN  NaN  NaN          NaN  1/1/01 0:05  41.887566 -87.711323
191637  NaN  NaN  NaN  NaN          NaN  1/1/01 0:01  41.981924 -87.658878
191638  NaN  NaN  NaN  NaN          NaN  1/1/01 0:01  41.799024 -87.696538
191639  NaN  NaN  NaN  NaN          NaN  1/1/01 0:01  41.971437 -87.727056
191640  NaN  NaN  NaN  NaN          NaN  1/1/01 0:01  41.968327 -87.696388

[191790 rows x 8 columns]

In [195]:
# concatenate dataframe horizontally
pd.concat([df,df1],axis="columns")

5.1  3.5  1.4  0.2  Iris-setosa            Date   Latitude  Longitude
0       4.9  3.0  1.4  0.2  Iris-setosa  12/31/12 23:15  41.756284 -87.621645
1       4.7  3.2  1.3  0.2  Iris-setosa  12/31/12 22:00  41.898788 -87.661303
2       4.6  3.1  1.5  0.2  Iris-setosa  12/31/12 22:00  41.969186 -87.767670
3       5.0  3.6  1.4  0.2  Iris-setosa  12/31/12 22:00  41.769329 -87.657726
4       5.4  3.9  1.7  0.4  Iris-setosa  12/31/12 21:30  41.837568 -87.621761
...     ...  ...  ...  ...          ...             ...        ...        ...
191636  NaN  NaN  NaN  NaN          NaN     1/1/01 0:05  41.887566 -87.711323
191637  NaN  NaN  NaN  NaN          NaN     1/1/01 0:01  41.981924 -87.658878
191638  NaN  NaN  NaN  NaN          NaN     1/1/01 0:01  41.799024 -87.696538
191639  NaN  NaN  NaN  NaN          NaN     1/1/01 0:01  41.971437 -87.727056
191640  NaN  NaN  NaN  NaN          NaN     1/1/01 0:01  41.968327 -87.696388

[191641 rows x 8 columns]

In [203]:
# get rows matching a condition
df1.query('Latitude>42')

Date   Latitude  Longitude
48      12/30/12 18:30  42.005517 -87.668482
76       12/30/12 1:30  42.016930 -87.687660
536     12/18/12 18:00  42.001401 -87.675261
669      12/15/12 3:00  42.011981 -87.674386
734     12/13/12 19:00  42.009242 -87.665404
...                ...        ...        ...
191092   1/11/01 22:45  42.007848 -87.675882
191191    1/9/01 18:30  42.003793 -87.667970
191373    1/5/01 22:30  42.009538 -87.681955
191452    1/4/01 18:00  42.006444 -87.680901
191492    1/3/01 22:30  42.010417 -87.674421

[2942 rows x 3 columns]

In [204]:
#DROP COLUMNS BY NAME 
df1.drop(columns=['Latitude'])

Date  Longitude
0       12/31/12 23:15 -87.621645
1       12/31/12 22:00 -87.661303
2       12/31/12 22:00 -87.767670
3       12/31/12 22:00 -87.657726
4       12/31/12 21:30 -87.621761
...                ...        ...
191636     1/1/01 0:05 -87.711323
191637     1/1/01 0:01 -87.658878
191638     1/1/01 0:01 -87.696538
191639     1/1/01 0:01 -87.727056
191640     1/1/01 0:01 -87.696388

[191641 rows x 2 columns]

In [205]:
#rename columns 
df1.rename(columns={"Date":"~Dated~"})

~Dated~   Latitude  Longitude
0       12/31/12 23:15  41.756284 -87.621645
1       12/31/12 22:00  41.898788 -87.661303
2       12/31/12 22:00  41.969186 -87.767670
3       12/31/12 22:00  41.769329 -87.657726
4       12/31/12 21:30  41.837568 -87.621761
...                ...        ...        ...
191636     1/1/01 0:05  41.887566 -87.711323
191637     1/1/01 0:01  41.981924 -87.658878
191638     1/1/01 0:01  41.799024 -87.696538
191639     1/1/01 0:01  41.971437 -87.727056
191640     1/1/01 0:01  41.968327 -87.696388

[191641 rows x 3 columns]

In [207]:
#add a new column
df.assign(flower_stem=9/5*df['1.4']+2)

5.1  3.5  1.4  0.2     Iris-setosa  flower_stem
0    4.9  3.0  1.4  0.2     Iris-setosa         4.52
1    4.7  3.2  1.3  0.2     Iris-setosa         4.34
2    4.6  3.1  1.5  0.2     Iris-setosa         4.70
3    5.0  3.6  1.4  0.2     Iris-setosa         4.52
4    5.4  3.9  1.7  0.4     Iris-setosa         5.06
..   ...  ...  ...  ...             ...          ...
144  6.7  3.0  5.2  2.3  Iris-virginica        11.36
145  6.3  2.5  5.0  1.9  Iris-virginica        11.00
146  6.5  3.0  5.2  2.0  Iris-virginica        11.36
147  6.2  3.4  5.4  2.3  Iris-virginica        11.72
148  5.9  3.0  5.1  1.8  Iris-virginica        11.18

[149 rows x 6 columns]

In [215]:
#calculate mean of each column 
df.mean()

C:\Users\ndhan\AppData\Local\Temp\ipykernel_15904\1587966387.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


5.1    5.848322
3.5    3.051007
1.4    3.774497
0.2    1.205369
dtype: float64

In [213]:
#get summary statistics by column
df.agg('3.5')

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
      ... 
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: 3.5, Length: 149, dtype: float64

In [211]:
#get unique rows
df.drop_duplicates()


5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[146 rows x 5 columns]

In [216]:
df.sort_values(by='3.5')

5.1  3.5  1.4  0.2      Iris-setosa
59   5.0  2.0  3.5  1.0  Iris-versicolor
61   6.0  2.2  4.0  1.0  Iris-versicolor
118  6.0  2.2  5.0  1.5   Iris-virginica
67   6.2  2.2  4.5  1.5  Iris-versicolor
92   5.0  2.3  3.3  1.0  Iris-versicolor
..   ...  ...  ...  ...              ...
15   5.4  3.9  1.3  0.4      Iris-setosa
13   5.8  4.0  1.2  0.2      Iris-setosa
31   5.2  4.1  1.5  0.1      Iris-setosa
32   5.5  4.2  1.4  0.2      Iris-setosa
14   5.7  4.4  1.5  0.4      Iris-setosa

[149 rows x 5 columns]

In [219]:
# get rows with largest values in a column
df.nlargest(10,'0.2')

5.1  3.5  1.4  0.2     Iris-setosa
99   6.3  3.3  6.0  2.5  Iris-virginica
108  7.2  3.6  6.1  2.5  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
113  5.8  2.8  5.1  2.4  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
114  6.4  3.2  5.3  2.3  Iris-virginica
117  7.7  2.6  6.9  2.3  Iris-virginica
119  6.9  3.2  5.7  2.3  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica